const TYPES = {
  KeyDataAgent: Symbol.for('KeyDataAgent'),
  EthPubKeyAgent: Symbol.for('EthPubKeyAgent'),
  EthPubKeyUseCase: Symbol.for('EthPubKeyUseCase'),
  TransactionSigner: Symbol.for('TransactionSigner'),
  AttributeDataAgent: Symbol.for('AttributeDataAgent'),
  AttributeUseCase: Symbol.for('AttributeUseCase'),
  ContractArtifacts: Symbol.for('ContractArtifacts'),
  CompanyDataAgent: Symbol.for('CompanyDataAgent'),
  CompanyUseCase: Symbol.for('CompanyUseCase'),
  RegistryCacheDataAgent: Symbol.for('RegistryCacheDataAgent'),
  NewOwnerDataAgent: Symbol.for('NewOwnerDataAgent'),
  TransferDataAgent: Symbol.for('TransferDataAgent'),
  NewResolverDataAgent: Symbol.for('NewResolverDataAgent'),
  AddrChangedDataAgent: Symbol.for('AddrChangedDataAgent'),
  ABIChangedDataAgent: Symbol.for('ABIChangedDataAgent'),
  EthPubKeyAddedDataAgent: Symbol.for('EthPubKeyAddedDataAgent'),
  EthPubKeyRevokedDataAgent: Symbol.for('EthPubKeyRevokedDataAgent'),
  KomgoMessagingPubKeyAddedDataAgent: Symbol.for('KomgoMessagingPubKeyAddedDataAgent'),
  KomgoMessagingPubKeyRevokedDataAgent: Symbol.for('KomgoMessagingPubKeyRevokedDataAgent'),
  VaktMessagingPubKeyAddedDataAgent: Symbol.for('VaktMessagingPubKeyAddedDataAgent'),
  VaktMessagingPubKeyRevokedDataAgent: Symbol.for('VaktMessagingPubKeyRevokedDataAgent'),
  NodeKeysChangedDataAgent: Symbol.for('NodeKeysChangedDataAgent'),
  TextChangedDataAgent: Symbol.for('TextChangedDataAgent'),
  StaticIdChangedDataAgent: Symbol.for('StaticIdChangedDataAgent'),
  IsFinancialInstitutionChangedDataAgent: Symbol.for('IsFinancialInstitutionChangedDataAgent'),
  IsMemberChangedDataAgent: Symbol.for('IsMemberChangedDataAgent'),
  MemberTypeChangedDataAgent: Symbol.for('MemberTypeChangedDataAgent'),
  VaktStaticIdChangedDataAgent: Symbol.for('VaktStaticIdChangedDataAgent'),
  KomgoMnidChangedDataAgent: Symbol.for('KomgoMnidChangedDataAgent'),
  X500NameChangedDataAgent: Symbol.for('X500NameChangedDataAgent'),
  ReverseNodeChangedDataAgent: Symbol.for('ReverseNodeChangedDataAgent'),
  VaktMnidChangedDataAgent: Symbol.for('VaktMnidChangedDataAgent'),
  HasSWIFTKeyChangedDataAgent: Symbol.for('HasSWIFTKeyChangedDataAgent'),
  MemberDAO: Symbol.for('MemberDAO'),
  RegistryEventManagerDAO: Symbol.for('RegistryEventManagerDAO'),
  RegistryEventProcessedDataAgent: Symbol.for('RegistryEventProcessedDataAgent'),
  IsDeactivatedChangedDataAgent: Symbol.for('IsDeactivatedChangedDataAgent'),
  KomgoProductsChangedDataAgent: Symbol.for('KomgoProductsChangedDataAgent'),
  RegistryCachePopulationService: Symbol.for('RegistryCachePopulationService'),
  CachePopulationStateHolder: Symbol.for('CachePopulationStateHolder'),
  PollingServiceFactory: Symbol.for('PollingServiceFactory'),

  DecoratorService: Symbol.for('DecoratorService'),
  CacheEventService: Symbol.for('CacheEventService'),
  MessagingFactory: Symbol.for('MessagingFactory'),

  EventsProcessor: Symbol.for('EventsProcessor'),
  Web3: Symbol.for('Web3'),
  Web3Wrapper: Symbol.for('Web3Wrapper'),
  SignerClient: Symbol.for('SignerClient'),
  BlockchainSignerClient: Symbol.for('BlockchainSignerClient')
}

export { TYPES }
