export const OVERRIDE_STANDARD_TEMPLATE = `FOR PAYMENT AT SIGHT BUT NOT BEFORE THE 31ST DAY AFTER B/L DATE OR DELIVERY DATE (SUCH DATE TO COUNT AS DAY ZERO) AGAINST PRESENTATION OF THE FOLLOWING DOCUMENTS:

1) A STATEMENT FOR AND ON BEHALF OF (BENEFICIARY) READING AS FOLLOWS:

'WE CERTIFY THAT THE AMOUNT OF US DOLLARS ....................  (INVOICE AMOUNT OR SUCH PART AS REMAINS UNPAID TO BE INSERTED) HAS REMAINED UNPAID AND IS NOW OVERDUE TO US UNDER THE TERMS OF OUR CONTRACT WITH (APPLICANT) FOR THE SALE OF ........................ BBLS/MT (WHICH EVER IS APPLICABLE) OF (GRADE) CRUDE OIL'

2) COPY OF SELLER'S COMMERCIAL INVOICE IN RESPECT OF SHIPMENT OR DELIVERY OF ..................... BBL/MT (WHICH EVER IS APPLICABLE) OF (GRADE) CRUDE OIL LOADED ON THE VESSEL TBN/SUB AND/OR DELIVERED AS PER CONTRACT

3) A STATEMENT FOR AND ON BEHALF OF (BENEFICIARY) READING AS FOLLOWS:

'WE CERTIFY THAT ALL THE SHIPPING DOCUMENTS, INCLUDING – WHERE APPLICABLE - FULL SET OF ORIGINAL B/L DULY ISSUED/ENDORSED TO THE ORDER OF (ISSUING BANK / APPLICANT), CALLED FOR IN THE CONTRACT REFERRED TO ABOVE HAVE BEEN FORWARDED TO (ISSUING BANK NAME AND ADDRESS) OR, IN THEIR ABSENCE, SELLER'S LETTER OF INDEMNITY AND / OR WARRANTY OF TITLE WHERE APPLICABLE SENT DIRECTLY TO THE BUYER'

DOCUMENTS PRESENTED VIA EMAIL (AS PDF), SWIFT, TELEX, FAX FORM OR ANY SECURE ELECTRONIC MEANS ARE ACCEPTABLE.

THE VALUE OF THIS STAND-BY LETTER OF CREDIT WILL AUTOMATICALLY BE REDUCED (BY PROVISIONAL INVOICE) OR CANCELLED (BY FINAL INVOICE) UPON PAYMENT OF INVOICE(S) IN FAVOUR OF THE BENEFICIARY BEARING REFERENCE TO THIS STAND-BY LETTER OF CREDIT, WHETHER SUCH PAYMENT(S):

1) ARE MADE PURSUANT TO THE PRESENTATION OF THE DOCUMENTS REQUESTED IN THIS STAND-BY LETTER OF CREDIT

2) OR ARE MADE BY THE APPLICANT TO THE BENEFICIARY THROUGH THE ISSUING BANK OR THROUGH ANOTHER APPLICANT’S BANK.

TYPOGRAPHICAL AND SPELLING ERRORS NOT TO BE CONSIDERED AS DISCREPANCIES, EXCEPT IN FIGURES.

REIMBURSEMENT CLAUSE:

UPON RECEIPT AT OUR COUNTERS OF DOCUMENTS AND PROVIDED WE RECOGNISE THEM ISSUED IN STRICT CONFORMITY WITH THE TERMS AND CONDITIONS OF THIS STAND-BY LETTER OF CREDIT, WE UNDERTAKE TO COVER YOU AS PER YOUR INSTRUCTIONS BY PAYING VALUE 2 (TWO) (ISSUING BANK CITY) / NEW YORK BANK WORKING DAYS AFTER OUR RECEIPT OF SUCH CONFORM DOCUMENTS.

OTHERWISE PAYMENT WILL BE EFFECTED VALUE TWO (ISSUING BANK CITY) / NEW YORK BANK WORKING DAYS AFTER RECEIPT OF SUCH COMPLIANT DOCUMENTS.

FOR PAYMENT(S) DUE ON A SUNDAY, OR ON A MONDAY WHICH IS A NEW YORK BANK HOLIDAY, THE PAYMENT(S) SHALL BE MADE ON THE NEXT NEW YORK BANKING DAY AFTER SUCH PAYMENT(S) DUE DATE.

FOR PAYMENT(S) DUE ON A SATURDAY, OR ON A NEW YORK BANK HOLIDAY OTHER THAN A MONDAY, THE PAYMENT(S) SHALL BE MADE ON THE LAST NEW YORK BANKING DAY PRIOR TO SUCH PAYMENT DUE DATE.

THE AMOUNT OF THIS STAND-BY LETTER OF CREDIT WILL AUTOMATICALLY FLUCTUATE IN ACCORDANCE WITH THE LOADED AND / OR DELIVERED QUANTITY AND THE CONTRACTUAL PRICE FORMULA EVEN ABOVE AND BELOW THE STATED LIMITS AND WITHOUT ANY FURTHER AMENDMENT.
          

ADDITIONAL CONDITIONS:

DOCUMENTS PRESENTED AFTER 21 DAYS AFTER THE DATE OF BILL OF LADING OR DELIVERY BUT WITHIN VALIDITY OF THIS STAND-BY LETTER OF CREDIT ARE ACCEPTABLE.

THE CONSTRUCTION, PERFORMANCE AND VALIDITY OF THIS STAND-BY LETTER OF CREDIT SHALL BE GOVERNED BY AND CONSTRUED IN ACCORDANCE WITH ENGLISH LAW.

ANY CLAIM OR DISPUTE ARISING OUT OF OR IN CONNECTION WITH THIS STAND-BY LETTER OF CREDIT SHALL BE SUBJECT TO THE EXCLUSIVE JURISDICTION OF THE ENGLISH COURTS.

THIS STAND-BY LETTER OF CREDIT IS SUBJECT TO THE UNIFORM CUSTOMS AND PRACTICE FOR DOCUMENTARY CREDITS (2007 REVISION - I.C.C. PUBLICATION NO. 600).

THIS MESSAGE IS THE OPERATIVE INSTRUMENT AND NO MAIL CONFIRMATION WILL FOLLOW.`
