stages:
  - setup
  - audit
  - test

install deps:
  cache:
    key: node_modules_cache
    paths:
    - node_modules/
  stage: setup
  script:
    - npm install
  only:
    - /^KOMGO-.*$/
    - /^cherry-pick-.*$/
    - develop
  artifacts:
    paths:
      - node_modules/
  tags:
    - node8

run audit:
  stage: audit
  script:
    - npm audit --registry=https://registry.npmjs.org
  only:
    - /^KOMGO-.*$/
    - /^cherry-pick-.*$/
    - develop
  dependencies:
    - install deps
  tags:
    - node8

run lint and formatting checks:
  stage: test
  script:
    - npm run tslint:ci
    - npm run check-formatting
  artifacts:
    paths:
      - report-lint.json
  only:
    - /^KOMGO-.*$/
    - /^cherry-pick-.*$/
    - develop
  except:
    - schedules
  tags:
    - node8

run tests:
  stage: test
  script:
    - npm run test:coverage
  artifacts:
    paths:
      - test-report.xml
      - coverage
  only:
    - /^KOMGO-.*$/
    - /^cherry-pick-.*$/
    - develop
  except:
    - schedules
  tags:
    - node8
