version: '3.4'

services:

  blockchain:
    image: ${IMAGE_NAME:-komgo-member-blockchain}
    build:
      context: ${BUILD_DIR:-./komgo-member-blockchain}
      dockerfile: Dockerfile-contracts
      args:
        NPM_TOKEN: $NPM_TOKEN
    container_name: komgo-blockchain
    command: sh /opt/truffle_migrate.sh
    environment:
      - CONTAINER_HOSTNAME=blockchain
      - BLOCKCHAIN_HOST
      - BLOCKCHAIN_PORT=22002
      - NPM_TOKEN
      - KALEIDO_USER
      - KALEIDO_PASSWORD
      - ENS_REGISTRY_CONTRACT_ADDRESS
    ports:
      - 9230:9229
    volumes:
      - ~/.bash_history:/root/.bash_history
      - ./kg-tools/.bashrc:/root/.bashrc
      - ./.db/contracts:/opt/build/contracts

networks:
  default:
    external:
      name: komgo
