version: "3.4"

services:
  lms-router:
    build: ./komgo-lms-router
    image: ${IMAGE_NAME:-komgo-member-lms-router}
    container_name: komgo-member-${MEMBER_ID}-lms-router
    restart: always
    environment:
      - MEMBER_1_STATIC_ID
      - MEMBER_2_STATIC_ID
      - DOCKER_HOST_MACHINE
      - API_ROLES_BASE_URL
      - API_AUTH_BASE_URL
      - API_REGISTRY_BASE_URL
    ports:
      - ${PORT_1:-3330}:8080

networks:
  default:
    external:
      name: komgo-${MEMBER_ID}
