version: "3.4"

services:
  api-blockchain-signer:
    image: ${IMAGE_NAME:-komgo-member-api-blockchain-signer}
    container_name: komgo-member-${MEMBER_ID}-api-blockchain-signer
    build:
      context: ${BUILD_DIR:-./komgo-member-api-blockchain-signer}
      args:
        NPM_TOKEN: $NPM_TOKEN
    restart: always
    environment:
      - NPM_TOKEN
      - BLOCKCHAIN_SCHEMA
      - BLOCKCHAIN_HOST
      - BLOCKCHAIN_PORT
      - BLOCKCHAIN_USER
      - BLOCKCHAIN_PASSWORD
      - CONTAINER_HOSTNAME=api-blockchain-signer
      - DB_MONGO_URL=mongodb://mongo:27017/api-signer${MONGO_CLIENT_OPTIONS}
      - ETH_KEYSTORE_PASSPHRASE=passphrase
      - PASSPHRASE=passphrase
      - MNEMONIC=buyer try humor into improve thrive fruit funny skate velvet vanish live
      - LOGSTASH_HOST
      - LOGSTASH_PORT
      - MONGO_CLIENT_PEM_BASE64
      - MONGO_CA_CERT_BASE64
      - MONGO_CLIENT_KEY_PASSWORD
      - MONGO_USE_SSL
      - INTERNAL_MQ_HOST
      - INTERNAL_MQ_USERNAME
      - INTERNAL_MQ_PASSWORD
      - VAULT_BASE_URL
      - API_BLOCKCHAIN_SIGNER_VAULT_ROLE_ID
      - API_BLOCKCHAIN_SIGNER_VAULT_SECRET_ID
    command: ${COMMAND:-komgo}
    ports:
      - ${PORT_1:-3112}:8080
      - ${PORT_2:-9142}:9229
    volumes:
      - ${MOUNT_VOLUME:-./komgo-member-api-blockchain-signer:/opt/app:delegated}
      - ~/.bash_history:/root/.bash_history
      - ./kg-tools/.bashrc:/root/.bashrc

networks:
  default:
    external:
      name: komgo-${MEMBER_ID}
