version: '3.4'

services:

  common-rabbit-node:
    image: rabbitmq:3.7.8-management-alpine
    container_name: komgo-common-mq
    volumes:
      - ${PWD}/komgo-member-mq/config/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ${PWD}/komgo-member-mq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ${PWD}/komgo-member-mq/config/http-length-mod/plugins/rabbitmq_management_komgo-3.7.8.ez:/opt/rabbitmq/plugins/rabbitmq_management-3.7.8.ez:ro
      - ./.db/rabbitmqdata/common-node:/var/lib/rabbitmq/mnesia
    ports:
      - 5673:5672
      - 15673:15672

  # We run this service in order to create the admin user once the bootstrap node of the cluster (komgo-internal-mq-node-1) is up and running
  configure-dev-common:
    build:
      context: ./komgo-member-mq/config
      dockerfile: Dockerfile.create.admin
    container_name: komgo-common-mq-config
    restart: on-failure
    environment:
      - MQ_NODE_HOST=${COMMON_MQ_HOST}
      - MQ_NODE_PORT=$COMMON_MQ_MANAGEMENT_PORT
      - ADMIN=${COMMON_MQ_USERNAME}
      - PW_SEED=${COMMON_MQ_PASSWORD}
    volumes:
      - ${PWD}/komgo-member-mq/config/wait-for-it:/usr/local/bin/wait-for-it:ro
      - ${PWD}/komgo-member-mq/config/create-admin:/usr/local/bin/create-admin:ro
      - ${PWD}/komgo-member-mq/config/password-hash-gen:/usr/local/bin/password-hash-gen:ro
      - ${PWD}/komgo-member-mq/config/setup-member:/usr/local/bin/setup-member:ro
    command: >
      bash -c "wait-for-it $COMMON_MQ_HOST:$COMMON_MQ_MANAGEMENT_PORT && create-admin"

networks:
  default:
    external:
      name: komgo
