version: '3.4'

services:

  event-management:
    image: ${IMAGE_NAME:-komgo-member-event-management}
    build:
      context: ${BUILD_DIR:-./komgo-member-event-management}
      args:
        NPM_TOKEN: $NPM_TOKEN
        NODE_ENV: development
    container_name: komgo-member-${MEMBER_ID}-event-management
    environment:
      - NPM_TOKEN
      - NODE_ENV=development
      - DB_MONGO_URL=mongodb://mongo/event-management${MONGO_CLIENT_OPTIONS}
      - CONTAINER_HOSTNAME=event-management
      - COMMON_MQ_BASE_URL
      - COMMON_MQ_USERNAME
      - COMMON_MQ_PASSWORD
      - INTERNAL_MQ_HOST
      - INTERNAL_MQ_USERNAME
      - INTERNAL_MQ_PASSWORD
      - INTERNAL_MQ_TO_PUBLISHER_ID
      - INTERNAL_MQ_FROM_PUBLISHER_ID
      - INTERNAL_MQ_CONSUMER_ID
      - API_SIGNER_BASE_URL
      - API_REGISTRY_BASE_URL
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - OUTBOUND_ROUTING_KEY
      - OUTBOUND_VAKT_EXCHANGE
      - COMPANY_STATIC_ID
      - LOGSTASH_HOST
      - LOGSTASH_PORT
      - MONGO_CLIENT_PEM_BASE64
      - MONGO_CA_CERT_BASE64
      - MONGO_CLIENT_KEY_PASSWORD
      - MONGO_USE_SSL
      - MESSAGE_AUDIT_WRITE_TIMEOUT
    command: ${COMMAND:-komgo}
    ports:
      - ${PORT_1:-3117}:8080
      - ${PORT_2:-9139}:9229
    volumes:
      - ${MOUNT_VOLUME:-./komgo-member-event-management:/opt/app:delegated}
      - ~/.bash_history:/root/.bash_history
      - ./kg-tools/.bashrc:/root/.bashrc


networks:
  default:
    external:
      name: komgo-${MEMBER_ID}
