version: '3.4'

services:

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:${ELK_VERSION}
    container_name: komgo-member-${MEMBER_ID}-logstash
    volumes:
      - ./komgo-member-logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./komgo-member-logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - ${PORT_1:-1514}:1514
      - ${PORT_2:-9600}:9600
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m

networks:
  default:
    external:
      name: komgo-${MEMBER_ID}
