version: '3.4'

services:

  vault:
    build:
      context: ./komgo-member-vault
      args:
        - VAULT_GIT_COMMIT
        - VAULT_GIT_DIRTY
    container_name: komgo-member-${MEMBER_ID}-vault
    restart: always
    cap_add:
      - IPC_LOCK
    volumes:
      - .db/vaultdata/member-${MEMBER_ID}/audit:/vault/audit:rw
      - .db/vaultdata/member-${MEMBER_ID}/storage:/vault/storage:rw
      - ./komgo-member-vault/config/dev.json:/vault/config/vault.json:ro
      - ./komgo-member-vault/plugins:/vault/plugins-ext:rw
    entrypoint: /bin/sh -c 'cp /vault/plugins/* /vault/plugins-ext && vault server -config /vault/config/vault.json'
    ports:
      - ${PORT_1:-8200}:8200

  configure-dev-vault:
    build:
      context: ./komgo-member-vault/config
      dockerfile: Dockerfile.dev
    container_name: komgo-member-${MEMBER_ID}-vault-config
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_BASE_DIR=/vault/provision
    volumes:
      - .db/vaultdata/member-${MEMBER_ID}/provision:/vault/provision:rw
      - ./komgo-member-vault/config/wait-for-it:/usr/local/bin/wait-for-it:ro
      - ./komgo-member-vault/vault-api.sh:/usr/local/bin/vault-api:ro
      - ./komgo-member-vault/plugins:/vault/provision/plugins:ro
    command: >
      bash -c "wait-for-it vault:8200 && vault-api base-config"
    restart: on-failure
networks:
  default:
    external:
      name: komgo-${MEMBER_ID}
