version: '3.4'

services:

  harbor-mock:
    image: ${IMAGE_NAME:-komgo-harbor-mock}
    container_name: komgo-member-${MEMBER_ID}-harbor-mock
    build:
      context: ${BUILD_DIR:-./harbor-mock}
      args:
        NPM_TOKEN: $NPM_TOKEN
    restart: always
    environment:
      - NPM_TOKEN
      - CONTAINER_HOSTNAME=harbor-mock
    command: ${COMMAND:-komgo}
    ports:
      - ${PORT_1:-3119}:8080
    volumes:
      - ${MOUNT_VOLUME:-./harbor-mock:/opt/app:delegated}
      - ~/.bash_history:/root/.bash_history
      - ./kg-tools/.bashrc:/root/.bashrc

networks:
  default:
    external:
      name: komgo-${MEMBER_ID}
