version: "3.4"

services:
  api-gateway:
    build: ./komgo-member-api-gateway
    image: ${IMAGE_NAME:-komgo-member-api-gateway}
    container_name: komgo-member-${MEMBER_ID}-api-gateway
    restart: always
    environment:
      - DEBUG=true
      - ACCESS_CONTROL_ALLOW_ORIGIN
      - API_USERS_BASE_URL
      - API_ROLES_BASE_URL
      - API_NOTIF_BASE_URL
      - API_AUTH_BASE_URL
      - API_SIGNER_BASE_URL
      - API_BLOCKCHAIN_SIGNER_BASE_URL
      - API_DOCUMENTS_BASE_URL
      - API_TRADE_CARGO_BASE_URL
      - API_TRADE_FINANCE_BASE_URL
      - API_REGISTRY_BASE_URL
      - API_COVERAGE_BASE_URL
      - API_MAGIC_LINK_BASE_URL
      - API_PRODUCTS_BASE_URL
      - WS_SERVER_BASE_URL
      - API_RECEIVABLE_FINANCE_BASE_URL
      - API_CREDIT_LINES_BASE_URL
      - API_ONBOARDING_BASE_URL
      - API_TEMPLATE_BASE_URL
      - API_AUTH_PATH=/authorize
      - ALLOW_SWAGGER_ACCESS=true
      - ENABLE_UNAUTHORIZED_ACCESS=true
    ports:
      - ${PORT_1:-3333}:8080

networks:
  default:
    external:
      name: komgo-${MEMBER_ID}
