version: '3.4'

services:
  client:
    image: ${IMAGE_NAME:-komgo-member-client}
    build:
      context: ${BUILD_DIR:-./komgo-member-client}
      args:
        NPM_TOKEN: $NPM_TOKEN
    container_name: komgo-member-${MEMBER_ID}-client
    restart: always
    command: ${COMMAND:-nginx-fe}
    ports:
      - ${PORT_1:-3010}:8080
      # - ${PORT_2:-5860}:5858
      # - ${PORT_3:-9232}:9229
    environment:
      - NPM_TOKEN
      - CONTAINER_HOSTNAME=client
      - PORT=8080
      - REACT_APP_API_GATEWAY_URL=${API_GATEWAY_SCHEME:-http}://$API_GATEWAY_HOST:$API_GATEWAY_PORT
      - REACT_APP_KEYCLOAK_REALM_NAME=$KEYCLOAK_REALM_NAME
      - REACT_APP_KEYCLOAK_AUTH_URL=$KEYCLOAK_AUTH_URL
      - REACT_APP_KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID
      - REACT_APP_ZENDESK_CLIENT_ID=$ZENDESK_CLIENT_ID
      - REACT_APP_ZENDESK_REDIRECT_URI=$ZENDESK_REDIRECT_URI
      - REACT_APP_ZENDESK_BASE_URL=$ZENDESK_BASE_URL
      - REACT_APP_ZENDESK_SEVERITY_FIELD_ID=$ZENDESK_SEVERITY_FIELD_ID
      - REACT_APP_ZENDESK_STEPS_FIELD_ID=$ZENDESK_STEPS_FIELD_ID
      - REACT_APP_ALLOW_FEATURE_TOGGLES=$ALLOW_FEATURE_TOGGLES
      - REACT_APP_IS_KOMGO_NODE=$IS_KOMGO_NODE
      - REACT_APP_IS_LMS_NODE=$IS_LMS_NODE
      - REACT_APP_BUILD_ID=$BUILD_ID
    volumes:
      - ${MOUNT_VOLUME:-./komgo-member-client:/opt/app:delegated}
      - ~/.bash_history:/root/.bash_history
      - ./kg-tools/.bashrc:/root/.bashrc

networks:
  default:
    external:
      name: komgo-${MEMBER_ID}
