const TYPES = {
  NotificationManagerClient: Symbol.for('NotificationManagerClient'),
  NotificationClient: Symbol.for('NotificationClient'),
  CreditLineDataAgent: Symbol.for('CreditLineDataAgent'),
  CreditLineRequestDataAgent: Symbol.for('CreditLineRequestDataAgent'),
  DisclosedCreditLineDataAgent: Symbol.for('DisclosedCreditLineDataAgent'),
  SharedCreditLineDataAgent: Symbol.for('SharedCreditLineDataAgent'),
  CreditLineService: Symbol.for('CreditLineService'),
  ReceiveDisclosedService: Symbol.for('ReceiveDisclosedService'),
  CounterpartyClient: Symbol.for('CounterpartyClient'),
  CompanyClient: Symbol.for('CompanyClient'),
  CreditLineValidationService: Symbol.for('CreditLineValidationService'),
  EventProcessor: Symbol.for('EventProcessor'),
  MessagingFactory: Symbol.for('MessagingFactory'),
  RequestClient: Symbol.for('RequestClient'),
  MessageProcessorService: Symbol.for('MessageProcessorService'),
  ShareCreditLineService: Symbol.for('ShareCreditLineService'),
  CreditLineRequestService: Symbol.for('CreditLineRequestService'),
  CreditLineRequestTaskFactory: Symbol.for('CreditLineRequestTaskFactory'),
  TaskManagerClient: Symbol.for('TaskManagerClient'),
  RequestValidationService: Symbol.for('RequestValidationService'),
  NotificationFactory: Symbol.for('NotificationFactory'),
  DepositLoanNotificationFactory: Symbol.for('DepositLoanNotificationFactory'),
  CreditLineValidationFactory: Symbol.for('CreditLineValidationFactory'),
  DepositLoanService: Symbol.for('DepositLoanService'),
  DepositLoanDataAgent: Symbol.for('DepositLoanDataAgent'),
  ShareDepositLoanService: Symbol.for('ShareDepositLoanService'),
  SharedDepositLoanDataAgent: Symbol.for('SharedDepositLoanDataAgent'),
  DisclosedDepositLoanDataAgent: Symbol.for('DisclosedDepositLoanDataAgent'),
  DepositLoanRequestDataAgent: Symbol.for('DepositLoanRequestDataAgent'),
  DepositLoanRequestService: Symbol.for('DepositLoanRequestService'),
  DepositLoanValidationService: Symbol.for('DepositLoanValidationService')
}

export { TYPES }
