export enum ErrorName {
  SendToCommonMQBrokerFailed = 'SendToCommonMQBrokerFailed',
  GetFromCommonMQBrokerFailed = 'GetFromCommonMQBrokerFailed',
  CommonToInternalTechnicalError = 'CommonToInternalTechnicalError',
  CommonToInternalProcessingError = 'InternalToCommonInvalidMessage',
  CommonToInternalAuditingError = 'CommonToInternalAuditingError',
  InternalToCommonTechnicalError = 'InternalToCommonTechnicalError',
  InternalToCommonPayloadTooLargeError = 'InternalToCommonPayloadTooLargeError',
  InternalToCommonRecipientIsNotAMember = 'InternalToCommonRecipientIsNotAMember',
  InternalToCommonAuditingError = 'InternalToCommonAuditingError',

  InternalToCommonInvalidMessage = 'InternalToCommonInvalidMessage',
  CompanyRegistryInvalid = 'CompanyRegistryInvalid',
  CompanyRegistryNoMINDFromStaticId = 'CompanyRegistryNoMINDFromStaticId',
  CompanyRegistryNoEntryFromStaticId = 'CompanyRegistryNoEntryFromStaticId',
  CompanyRegistryNoPropertyFromMNID = 'CompanyRegistryNoPropertyFromMNID',
  CommonToInternalFailed = 'CommonToInternalFailed',
  InternalToCommonFailed = 'InternalToCommonFailed',
  GetMessageFromCommonQueueFailed = 'GetMessageFromCommonQueueFailed',
  InternalToCommonSignatureValidationDecryptFailed = 'InternalToCommonSignatureValidationDecryptFailed',
  InternalToCommonEmptyMessagePayload = 'InternalToCommonEmptyMessagePayload',
  InternalToCommonMalformedMessagePayload = 'InternalToCommonMalformedMessagePayload',
  SignerRequestFailed = 'SignerRequestFailed',
  CompanyRegistryRequestFailed = 'CompanyRegistryRequestFailed',
  ReadyCheck = 'ReadyCheck'
}
