stages:
  - setup

docker build and push:
  stage: setup
#  image: docker:stable-git # Uncomment this line if Gitlab shared runners
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375 # Comment this line if Gitlab shared runners
    REPOSITORY_URI:  hbr.solutions.consensys-uk.net/komgo
  script:
    - PROJECT_NAME=$(basename `git rev-parse --show-toplevel`)
    - SHORT_SHA=${CI_COMMIT_SHA:0:8}
    - echo "$SHORT_SHA"
    - IMAGE_ID=$(docker build --pull --quiet --tag $PROJECT_NAME:$SHORT_SHA .)
    - |
      if [[ $CI_COMMIT_REF_NAME = "develop" || $CI_COMMIT_REF_NAME = "release"* || $PUBLISH = "true" ]]; then
        echo $HARBOR_INFRABOT_PASSWORD | docker login $REPOSITORY_URI -u=infrabot --password-stdin
        docker tag $PROJECT_NAME:$SHORT_SHA $REPOSITORY_URI/$PROJECT_NAME:$SHORT_SHA      
        echo "Pushing to remote repository"
        docker --debug push $REPOSITORY_URI/$PROJECT_NAME:$SHORT_SHA
        rm -f /root/.docker/config.json
      fi
    - docker images
    - docker rmi -f $IMAGE_ID
  only:
    refs:
      - /^release-.*$/
      - develop
      - /^KOMGO-.*$/
  tags: # Comment this line if Gitlab shared runner
    - docker # Comment this line if Gitlab shared runner