export enum DocumentTypes {
  Invoice = 'invoice',
  Other = 'other',
  CommercialContract = 'commercialContract',
  CommercialContractAmendment = 'commercialContractAmendment',
  ProofOfPerformance = 'proofOfPerformance',
  ProofOfTradeAcceptance = 'proofOfTradeAcceptance',
  PaymentUndertaking = 'paymentUndertaking',
  RenunciationOfRights = 'renunciationOfRights',
  AssignmentOfProceeds = 'assignmentOfProceeds',
  ParentCompanyGuarantee = 'parentCompanyGuarantee',
  ProofOfDiscounting = 'proofOfDiscounting',
  DiscountingAgreement = 'mrpa',
  DiscountingAgreementAppendixes = 'mrpaAppendix',
  ProofOfRepayment = 'proofOfRepayment',
  InsurancePolicy = 'insurancePolicy',
  LostPayeeEvidence = 'lostPayeeEvidence',
  PaymentConfirmation = 'paymentConfirmation',
  BillOfExchange = 'billOfExchange',
  PromissoryNote = 'promissoryNote',
  AcknowledgementOfNoticeOfAssignment = 'noticeOfAssignment'
}
