version: '3.2'

services:

  # COMMON NODE ROUTER:
  common-router:
    image: komgo/rabbitmq-common-router
    build:
      context: .
    environment:
      - COMMON_BROKER_AMQP_URI=amqp://KomgoInternalUser:Tostoresomewhere@komgo-common-mq-node-1:5672/

networks:
  default:
    external:
      name: komgo
