#!/bin/sh

# Running compiled version:
if [ -f ./dist/index.js ]; then
  node ./dist/index.js $@

# Running development version:
else
  if [ ! -d ./node_modules ]; then
    echo "Run \"npm install\" for development version first!"
    exit 1
  fi
  ./node_modules/.bin/ts-node ./src/index.ts $@
fi
