stages:
  - setup
  - audit
  - test
  - slack_notification
  - analysis
  - update_and_test

install-dependencies:
  cache:
    key: node_modules_cache
    paths:
      - node_modules/
  stage: setup
  script:
    - npm install --ignore-scripts
  only:
    - /^KOMGO-.*$/
    - /^cherry-pick/
    - develop
    - /^release-.*$/
    - /^revert-.*$/
  artifacts:
    paths:
      - node_modules/
  tags:
    - node10

run audit:
  stage: audit
  # ignore dev tool vulnerabilities:
  # - Missing Origin Validation (https://nodesecurity.io/advisories/725)
  # - Regular Expression Denial of Service  (https://nodesecurity.io/advisories/786)
  script:
    - |
      if [[ $(npm audit --registry=https://registry.npmjs.org --parseable | grep -v "/advisories/725" | grep -v "/advisories/786" | wc -l) -gt 1 ]]; then
        npm audit --registry=https://registry.npmjs.org
      fi
  only:
    - /^KOMGO-.*$/
    - /^cherry-pick-.*$/
    - develop
    - /^release-.*$/
    - /^revert-.*$/
  dependencies:
    - install-dependencies
  allow_failure: true
  tags:
    - node10

docker build and push:
  stage: test
  #  image: docker:stable-git # Uncomment this line if Gitlab shared runners
  except:
    - schedules
  services:
    - docker:18.09-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375 # Comment this line if Gitlab shared runners
    REPOSITORY_URI: hbr.solutions.consensys-uk.net/komgo
  script:
    - echo $HARBOR_INFRABOT_PASSWORD | docker login $REPOSITORY_URI -u=infrabot --password-stdin
    - PROJECT_NAME=$(basename `git rev-parse --show-toplevel`)
    - SHORT_SHA=${CI_COMMIT_SHA:0:8}
    - echo "$SHORT_SHA"
    - IMAGE_ID=$(docker build --build-arg NPM_TOKEN=$NPM_TOKEN --pull --quiet --tag $PROJECT_NAME:$SHORT_SHA .)
    - |
      if [[ $CI_COMMIT_REF_NAME = "develop" || $CI_COMMIT_REF_NAME = "release"* || $PUBLISH = "true" ]]; then
        docker tag $PROJECT_NAME:$SHORT_SHA $REPOSITORY_URI/$PROJECT_NAME:$SHORT_SHA
        echo "Pushing to remote repository"
        docker --debug push $REPOSITORY_URI/$PROJECT_NAME:$SHORT_SHA
        rm -f /root/.docker/config.json
      fi
    - docker images
    - docker rmi -f $IMAGE_ID
  only:
    refs:
      - /^release-.*$/
      - develop
      - /^KOMGO-.*$/
      - /^cherry-pick/
      - /^revert-.*$/
  tags: # Comment this line if Gitlab shared runner
    - docker-node10 # Comment this line if Gitlab shared runner

lint:
  stage: test
  except:
    - schedules
  script:
    - npm run tslint:ci
  only:
    - /^KOMGO-.*$/
    - develop
    - /^cherry-pick/
    - /^release-.*$/
    - /^revert-.*$/
  artifacts:
    paths:
      - report-lint.json
  dependencies:
    - install-dependencies
  tags:
    - node10

formatting:
  stage: test
  except:
    - schedules
  script:
    - npm run check-formatting
  only:
    - /^KOMGO-.*$/
    - develop
    - /^cherry-pick/
    - /^release-.*$/
    - /^revert-.*$/
  dependencies:
    - install-dependencies
  tags:
    - node10

unit:
  stage: test
  except:
    - schedules
  script:
    - npm run test:coverage
  only:
    - /^KOMGO-.*$/
    - develop
    - /^cherry-pick/
    - /^release-.*$/
    - /^revert-.*$/
  artifacts:
    paths:
      - coverage
  dependencies:
    - install-dependencies
  tags:
    - node10

sonarqube:
  stage: analysis
  except:
    - schedules
  dependencies:
    - install-dependencies
    - unit
    - lint
  image: rvelaz/sonar-scanner:3.2.0.1227
  script:
    - |
      sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dproject.settings=sonar/sonar.properties \
                  -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA \
                  -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME \
                  -Dsonar.gitlab.project_id=$CI_PROJECT_ID \
                  -Dsonar.gitlab.user_token=$GITLAB_TOKEN
  only:
    - /^KOMGO-.*$/
    - develop
    - /^cherry-pick/
    - /^release-.*$/
    - /^revert-.*$/
  tags:
    - sonar

trigger update and e2e test develop branch:
  stage: update_and_test
  except:
    - schedules
  variables:
    NUMBER_OF_MEMBERS: 4
    QA_ENV: ci
    BRANCH: develop
    COUNTERPARTY: ing-ams
    COMPANY: bp-london
  script:
    - export COMMIT_AUTHOR=$(git show -s --format='%ae' $CI_COMMIT_SHA)
    - branch=$(echo $CI_COMMIT_TITLE | awk '{print $3}' | sed "s/'/ /g" | sed 's/ //g')
    - |
      response=$(curl https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests?state=merged -H "PRIVATE-TOKEN: $GITLAB_API_TOKEN" | jq '.[] | "\(.title) \(.source_branch)"' | (grep "$branch" || true) | head -n 1 | (grep BUILD_FIX || true) | wc -c | sed "s/[^0-9]//g")
      echo $response
      if [ "$response" -ne 0 ]; then
        export BUILD_FIX="true"
      else
        export BUILD_FIX="false"
      fi
    - curl -X POST -F token=$E2E_DEVELOP_TRIGGER_TOKEN -F ref=master -F "variables[DEPLOY_LATEST]=true" -F "variables[NUMBER_OF_MEMBERS]=${NUMBER_OF_MEMBERS}" -F "variables[UPDATE]=true" -F "variables[QA_ENV]=${QA_ENV}" -F "variables[BRANCH]=${BRANCH}" -F "variables[COMMIT_AUTHOR]=${COMMIT_AUTHOR}" -F "variables[COUNTERPARTY]=${COUNTERPARTY}" -F "variables[COMPANY]=${COMPANY}" -F "variables[BUILD_FIX]=${BUILD_FIX}" -F "variables[SOURCE_PIPELINE_URL]=${CI_PIPELINE_URL}" https://gitlab.com/api/v4/projects/9675386/trigger/pipeline
  only:
    refs:
      - develop
  tags:
    - deploy

trigger update and e2e test release branch:
  stage: update_and_test
  except:
    - schedules
  variables:
    NUMBER_OF_MEMBERS: 4
    QA_ENV: ci-re
    BRANCH: $CI_COMMIT_REF_NAME
    COUNTERPARTY: ing-ams
    COMPANY: bp-london
  script:
    - export COMMIT_AUTHOR=$(git show -s --format='%ae' $CI_COMMIT_SHA)
    - branch=$(echo $CI_COMMIT_TITLE | awk '{print $3}' | sed "s/'/ /g" | sed 's/ //g')
    - |
      response=$(curl https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests?state=merged -H "PRIVATE-TOKEN: $GITLAB_API_TOKEN" | jq '.[] | "\(.title) \(.source_branch)"' | (grep "$branch" || true) | head -n 1 | (grep BUILD_FIX || true) | wc -c | sed "s/[^0-9]//g")
      echo $response
      if [ "$response" -ne 0 ]; then
        export BUILD_FIX="true"
      else
        export BUILD_FIX="false"
      fi
    - curl -X POST -F token=$E2E_RELEASE_TRIGGER_TOKEN -F ref=master -F "variables[DEPLOY_LATEST]=true" -F "variables[NUMBER_OF_MEMBERS]=${NUMBER_OF_MEMBERS}" -F "variables[UPDATE]=true" -F "variables[QA_ENV]=${QA_ENV}" -F "variables[BRANCH]=${BRANCH}" -F "variables[COMMIT_AUTHOR]=${COMMIT_AUTHOR}" -F "variables[COUNTERPARTY]=${COUNTERPARTY}" -F "variables[COMPANY]=${COMPANY}" -F "variables[BUILD_FIX]=${BUILD_FIX}" -F "variables[SOURCE_PIPELINE_URL]=${CI_PIPELINE_URL}" https://gitlab.com/api/v4/projects/9555029/trigger/pipeline
  only:
    refs:
      - /^release-.*$/
  except:
    refs:
      - /^release-test$/
      - schedules
  tags:
    - deploy

notify slack on failure:
  stage: slack_notification
  script:
    - echo "CI_PIPELINE_URL $CI_PIPELINE_URL"
    - "curl -X POST \
      https://hooks.slack.com/services/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 \
      -H 'Content-Type: application/json' \
      -d '{
      \"text\": \":warning: CI AUDIT PIPELINE FAILED\",
      \"attachments\": [
      {
      \"author_name\": \"PIPELINE URL: '\"$CI_PIPELINE_URL\"'\",
      \"title\": \"Click here to check pipeline\",
      \"title_link\": \"'\"$CI_PIPELINE_URL\"'\",
      \"color\": \"danger\",
      \"image_url\": \"https://raw.githubusercontent.com/standard/standard/master/docs/logos/npm.png\"
      }
      ]
      }'"
  when: on_failure
  only:
    - schedules
  tags:
    - deploy
