export const OUTBOUND_MESSAGE_VERSION = 1
export const OUTBOUND_MESSAGE_TYPE_PREFIX = 'KOMGO.RFP.'

export const INTERNAL_MESSAGE_VERSION = 1
export const INTERNAL_MESSAGE_TYPE_PREFIX = 'INTERNAL.RFP.'
