import { ReplyType } from '@komgo/types'

export interface IReply {
  staticId: string
  type: ReplyType
  rdId: string
  participantId: string
  senderStaticId: string
  comment?: string
  quoteId?: string
  createdAt?: string
  updatedAt?: string
  autoGenerated?: boolean
}
