export const LOIText = `QUOTE

LETTER OF INDEMNITY

TO : APPLICANT

FROM: BENEFICIARY

DATE : XX

WE REFER TO OUR AGREEMENT DATED XXXXX IN RESPECT OF YOUR PURCHASE FROM US OF A CARGO OF XXXXXXX BARRELS OF XXXXXX (THE AGREEMENT) SHIPPED ON BOARD M/T XXXXXX AT XXXXXXX PURSUANT TO BILL OF LADING DATED XXXXXXXXX.

ALTHOUGH WE HAVE SOLD AND TRANSFERRED TITLE OF THE SAID CARGO TO YOURSELVES, WE HAVE BEEN UNABLE TO PROVIDE YOU WITH THE FULL SET OF ORIGINAL BILL OF LADING ISSUED OR ENDORSED TO THE ORDER OF XXXXX AND THE OTHER SHIPPING DOCUMENTS COVERING THE SAID SALE PURSUANT TO THE AGREEMENT (THE DOCUMENTS).

IN CONSIDERATION OF YOUR PAYING US DOLLARS XXXXXXX IN ACCORDANCE WITH THE AGREEMENT, WE HEREBY EXPRESSLY WARRANT THAT WE HAVE SOLD SUCH XXXXXXX TO YOU HAVING GOOD TITLE TO IT AND FULL RIGHT AND AUTHORITY TO TRANSFER SUCH TITLE TO YOU AND TO DELIVERY OF SUCH PRODUCT.

WE FURTHER UNDERTAKE TO MAKE ALL REASONABLE EFFORTS TO LOCATE AND SURRENDER TO YOU AS SOON AS POSSIBLE THE DOCUMENTS AND TO PROTECT, INDEMNIFY AND KEEP YOU HARMLESS FROM AND AGAINST ANY AND ALL DAMAGES, COST AND EXPENSES (INCLUDING REASONABLE ATTORNEY FEES), WHICH YOU MAY SUFFER BY REASON OF THE DOCUMENTS REMAINING OUTSTANDING, INCLUDING, BUT NOT LIMITED TO, ANY CLAIMS AND DEMANDS WHICH MAY BE MADE BY A HOLDER OR TRANSFEREE OF THE DOCUMENTS, OR BY ANY OTHER THIRD PARTY CLAIMING AN INTEREST IN OR LIEN ON THE CARGO OR PROCEEDS THEREOF ARISING OUT OF OR IN CONNECTION WITH THE DOCUMENTS OR A BREACH BY US OF ANY OF OUR WARRANTIES HEREIN.

OUR OBLIGATION TO INDEMNIFY YOU IS, OF COURSE, SUBJECT TO THE CONDITION THAT YOU GIVE US PROMPT NOTICE OF THE ASSERTION OF ANY CLAIM, FULL OPPORTUNITY TO CONDUCT THE DEFENCE THEREOF AND THAT YOU WILL NOT SETTLE ANY SUCH CLAIM WITHOUT OUR WRITTEN APPROVAL.

THIS LETTER OF INDEMNITY SHALL EXPIRE UPON OUR PRESENTING THE DOCUMENTS MENTIONED ABOVE TO THE ISSUING BANK.

THIS LETTER OF INDEMNITY SHALL BE GOVERNED BY AND CONSTRUED IN ACCORDANCE WITH THE LAWS OF ENGLAND AND IN THE EVENT OF ANY DISPUTES HEREUNDER IT SHALL BE SUBJECT TO THE EXCLUSIVE JURISDICTION OF THE ENGLISH HIGH COURT IN LONDON.

SIGNED

AUTHORISED SIGNATURE FOR AND ON BEHALF OF

BENEFICIARY

UNQUOTE`
