# if you're doing anything beyond your local machine, please pin this to a specific version at https://hub.docker.com/_/node/
FROM node:8-alpine

RUN mkdir -p /opt/contracts && mkdir /opt/migrations && mkdir -p /opt/build/contracts

# install Truffle and Swagger dependencies
RUN npm install -g truffle@v4.1.13

RUN apk add --no-cache jq git python make g++

ARG NPM_TOKEN

WORKDIR /opt

COPY .npmrc package.json package-lock.json* ./

RUN npm install && npm cache clean --force

COPY . .

RUN rm -f .npmrc

CMD [ "sh", "truffle_migrate.sh" ]
