export enum ACTIONS {
  GENERATE_ONE_TIME_KEY = 'GenerateOnetimeKey',
  POST_TRANSACTION = 'PostTransaction',
  ETH_GET_KEY = 'ETHGetNewKey',
  ETH_CREATE_NEW_KEY = 'ETHCreateNewKey',
  ETH_CREATE_NEW_ONETIME_KEY = 'ETHCreateNewOneTimeKey',
  INIT_KEY_DAT = 'InitKeyData',
  SEND_TX = 'SendTx',
  SIGN_TX = 'SignTx',
  ETH_SIGN = 'ETHSign',
  VERIFY_TX = 'VerifyTx',
  ENCRYPT = 'Encrypt',
  DECRYPT = 'Decrypt',
  BUILD_RAW_PUBLIC_TX = 'BuildRawPublicTx',
  BUILD_RAW_PRIVATE_TX = 'BuildRawPrivateTx',
  UPDATE_TX_NONCE = 'UpdateTxNonce',
  UNLOCK_ACCOUNT = 'UnlockAccount',
  RETRY_TX = 'RetryTx',
  BUILD_INDEX = 'BuildIndex',
  TX_GET_STATUS = 'TxGetStatus'
}

export enum ErrorName {
  NoETHKeyData = 'NoETHKeyData',
  VerifyUnconfirmedTxsFailed = 'VerifyUnconfirmedTxsFailed',
  Web3Error = 'Web3Error',
  SendTxFailed = 'SendTxFailed',
  SendTxReverted = 'SendTxReverted',
  InitKeyFromFileFailed = 'InitKeyFromFileFailed',
  ETHSignTxFailed = 'ETHSignTxFailed',
  ETHSimpleSignTxFailed = 'ETHSimpleSignTxFailed',
  ETHCheckSignatureFailed = 'ETHCheckSignatureFailed',
  OneTimeKeyGenFailed = 'OneTimeKeyGenFailed',
  ETHCreateKeyFailed = 'ETHCreateKeyFailed',
  CompanyKeyProviderInitKeyDataFailed = 'CompanyKeyProviderInitKeyDataFailed',
  ETHKeyNotFound = 'ETHKeyNotFound',
  PostTxFailed = 'PostTxFailed',
  PostPublicTxFailed = 'PostPublicTxFailed',
  PostPrivateTxFailed = 'PostPrivateTxFailed',
  BuildPublicTxFailed = 'BuildPublicTxFailed',
  BuildPrivateTxFailed = 'BuildPrivateTxFailed',
  InvalidLocalTxHash = 'InvalidLocalTxHash',
  ETHDecryptFailed = 'ETHDecryptFailed',
  ETHEncryptFailed = 'ETHEncryptFailed',
  InvalidRequestOrigin = 'InvalidRequestOrigin',
  DatabaseBuildIndexFailed = 'DatabaseBuildIndexFailed',
  PublishMessageFailed = 'PublishMessageFailed',
  UnlockAccountFailed = 'UnlockAccountFailed',
  MaxAttemptsReached = 'MaxTxRetriesAttemptsReached',
  UpdateTxStateFailed = 'UpdateTxStateFailed',
  TxNotFound = 'TransactionNotFound',
  TxStatus = 'TransactionStatusFailed',
  VaultIsNotAvailable = 'VaultIsNotAvailable',
  VaultAuthFailed = 'VaultAuthFailed',
  VaultWriteKVFailed = 'VaultWriteKVFailed',
  VaultReadKVFailed = 'VaultReadKVFailed',
  EthResetNonceFail = 'EthResetNonceFail'
}
