#!/bin/bash
#
# SPDX-License-Identifier: Apache-2.0
#

starttime=$(date +%s)

E_UUID="DEV-EXCHANGE"

echo "PUT a new exchange $E_UUID for organisation $ORG"
echo
    curl -i -u $ADMIN:$PW_SEED -H "content-type:application/json" \
    -XPUT -d'{"type":"topic","durable":true}' \
    "http://$MQ_NODE_HOST:$MQ_NODE_PORT/api/exchanges/%2F/$E_UUID"
echo
echo

DOCMGMT_Q_UUID="DEV-DOCMGMT.$E_UUID"

echo "PUT a new queue $DOCMGMT_Q_UUID for organisation $ORG"
echo
    curl -i -u $ADMIN:$PW_SEED -H \
    "content-type:application/json" \
    -XPUT -d"{\"type\":\"topic\",\"durable\":true, \"arguments\": {\"x-dead-letter-exchange\":	\"$E_UUID\", \"x-dead-letter-routing-key\":	\"DEV-DOCMGMT.dead\"}}" \
    "http://$MQ_NODE_HOST:$MQ_NODE_PORT/api/queues/%2F/$DOCMGMT_Q_UUID"
echo
echo

REQDOC_B="KOMGO.DOCUMENTS.RequestDocuments"

echo "POST a binding for $REQDOC_B for organisation $ORG between exchange $E_UUID and queue $DOCMGMT_Q_UUID"
echo
    curl -i -u $ADMIN:$PW_SEED -H "content-type:application/json" \
    -XPOST -d"{\"routing_key\":\"$REQDOC_B\", \"arguments\":{}}" \
    "http://$MQ_NODE_HOST:$MQ_NODE_PORT/api/bindings/%2F/e/$E_UUID/q/$DOCMGMT_Q_UUID"
echo
echo

SENDOC_B="KOMGO.DOCUMENTS.SendDocuments"

echo "POST a binding for $SENDOC_B for organisation $ORG between exchange $E_UUID and queue $DOCMGMT_Q_UUID"
echo
    curl -i -u $ADMIN:$PW_SEED -H "content-type:application/json" \
    -XPOST -d"{\"routing_key\":\"$SENDOC_B\", \"arguments\":{}}" \
    "http://$MQ_NODE_HOST:$MQ_NODE_PORT/api/bindings/%2F/e/$E_UUID/q/$DOCMGMT_Q_UUID"
echo
echo

echo "Total execution time : $(($(date +%s)-starttime)) secs ..."